apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: validate-phone-book-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validate-phone-book-container
  template:
    metadata:
      labels:
        app: validate-phone-book-container
        tier: backend
    spec:
      containers:
        - name: validate-phone-book-container
          image: validate-phone-book:latest
          ports:
            - containerPort: 8000
              protocol: TCP
          imagePullPolicy: Never